name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.OPEN5GS_USR }}
        password: ${{ secrets.DOCKER_OPEN5GS_TRUC }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag huutrucnguyen0508/truc_open5gs:$(date +%s)
