name: build-image

on:
  push:
    branches:
      - 'master'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TRUCKAT_IMG }}
          password: ${{ secrets.DOKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 21310174/TrucOpen5gs:1.0.6
